version: '3'

services:
  utils:
    build:
      context: .
    image: alpine_utils:latest
    privileged: true
    network_mode: host
    volumes:
      - "..:/home/Development"
      - "./local.kube/:/root/.kube/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/home/Development/"
    tty: true
    stdin_open: true
